name: Iac CI/CD Pipeline

on:
    push:
        branches:
            - main
        paths:
            - 's3-cdn-modules/**'

jobs:
    terraform:
        runs-on: ubuntu-latest
        outputs:
            s3_bucket_name: ${{ steps.get_bucket.outputs.s3_bucket_name }}
            cloudfront_domain_name: ${{ steps.get_cf.outputs.cloudfront_domain_name }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: latest
                  terraform_wrapper: false

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-2
                  
            - name: Initialize Terraform
              run: terraform -chdir=s3-cdn-modules init

            - name: Validate Terraform configuration
              run: terraform -chdir=s3-cdn-modules validate

            - name: Plan Terraform changes
              run: terraform -chdir=s3-cdn-modules plan -out=tfplan

            - name: Apply Terraform changes
              if: github.ref == 'refs/heads/main'
              run: terraform -chdir=s3-cdn-modules apply -auto-approve tfplan

            - name: get bucket output
              id: get_bucket
              run: |
                S3_Bucket_NAME=$(terraform -chdir=s3-cdn-modules output -raw s3_bucket_name)
                 echo s3_bucket_name=$S3_Bucket_NAME >> $GITHUB_OUTPUT

            - name: get cloudfront output
              id: get_cf
              run:  |
                CLOUDFRONT_DOMAIN_NAME=$(terraform -chdir=s3-cdn-modules output -raw cloudfront_domain_name)
                echo cloudfront_domain_name=$CLOUDFRONT_DOMAIN_NAME >> $GITHUB_OUTPUT


    Deploy_to_s3:
        runs-on: ubuntu-latest
        needs: terraform
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-2

            - name: Sync files to S3
              run: |
                  aws s3 sync . s3://${{ needs.terraform.outputs.s3_bucket_name }} \
                  --exclude "*" \
                  --include "index.html" \
                  --include "styles.css" \
                  --include "script.js" \
                  --delete
                